spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pass_vault
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
