spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pass_vault
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML5
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/,file:src/main/resources/templates/
      cache:
        period: 0
server:
  port: 8085